### PR TITLE
Import Exception class and other small fixes

### PR DESCRIPTION
**Pull request by magnusjt**
Just added missing import statement for Exception.

Also ran code through inspection tool, and fixed some other small issues. There's a ton more to fix as well.

### CODE REVIEW

**Comment by szymach** [comment]
Alright I guess I'll leave this PR until evening :P Thanks again :)

**Comment by szymach** [comment]
By the way what inspection tool are you using? I'm using php_codesniffer, but it seems it doesn't catch what your tool is. I may add it to Travis CI build to prevent such errors in the future.

**Comment by magnusjt** [comment]
It's just the built-in one in phpstorm. I'm not sure if it can be used as a standalone tool.

**Comment by szymach** [comment]
I was afraid so. Anyways, I'm merging this PR - if you have any other issues, don't hesitate to let me know.

**Comment by magnusjt** [comment]
Thanks :) The other issues were only with legacy code from pChart, so I don't think it's any point fixing them.

**Pull request merged**
