### PR TITLE
Add fixes for PHP 7.1 support - refs #1

### PR DESCRIPTION
**Pull request by ywarnier**

### CODE REVIEW

**Comment by szymach** [comment]
So is this an actual fix for 7.1 or a coding standard issue?

**Comment by ywarnier** [comment]
It's a fix for 7.1.
In 7.1, applying an empty string index operators to a string returns a fatal error. For some reason, you naturally removed most of these from version 1 to version 2 of c-pchart, but some were left. I'm not sure I found them all yet, but this PR doesn't add any issue and definitely removes 2.
http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.empty-string-index-operator

**Comment by szymach** [comment]
Reason is that I either did not notice them or were not sure if I can change it without a BC break. Feel free to root these out :)

**Comment by ywarnier** [comment]
Well, in the case of this PR, this is a direct fix for two huge fatal errors I had when using c-pchart, and doing the change fixed those, so there's no doubt here. I don't think (but I didn't check) that it breaks anything for PHP 5 either. Looking at the code, these variables are only ever used used as arrays :-)

**Comment by szymach** [comment]
I think you should also change [this](https://github.com/beeznest/c-pchart/blob/5e51794878be474695aa79edf5103540c89cef1e/src/Chart/Draw.php#L1158) line :) It may not break anything currently, but if we are aiming to make things consistent, then it will not hurt to do so.

**Comment by ywarnier** [comment]
True... true...
Change added.

**Pull request merged**
