### PR TITLE
Fixes change of FontName.

### PR DESCRIPTION
**Pull request by rgcouto**
If you try to change the FontName as below, the font won't change. I've changed the way the FontName gets assigned.

`        $image->setFontProperties(array("FontName"=>"calibri.ttf", "FontSize" => 10));`

### CODE REVIEW

**Comment by szymach** [comment]
Hey there,
[This](https://github.com/szymach/c-pchart/blob/08a2937e0b1f73f1105aa6fbd3f8873a1e43ed52/src/Image.php#L299) line does exactly what your changes do. Also, `$FontName` property has public access, so there is no need for adding getter and setter methods for it. You can simply change the value yourself should you wish to.

Lastly, can you provide me with a bigger code sample so I can test it myself and see that it does not work? Thanks.

**Comment by rgcouto** [comment]
Hey,

Thank you for your message. I've tried to debug the code and I found out that the line you've mentioned wouldn't change the font face, that's why I propose this change.

Below you'll find an extract of my code where I set a new font face (not the default one) that doesn't work without the changes I propose.

`/* Build a dataset */
        $data = new Data();
        $data->setAxisName(0, "X");
        $data->setAxisDisplay(0,AXIS_FORMAT_METRIC);
        $data->addPoints($timeseries->xData, "Date");
        $data->setSerieDescription("Date","Date");
        $data->setAbscissa("Date");
        $data->setXAxisDisplay(AXIS_FORMAT_DATE, "Y/m/d");

        /* Create the chart area */
        $image = new Image(800, 680, $data);
        $image->setFontProperties(array("FontName"=>"calibri.ttf", "FontSize" => 10));

        /* Create X chart */
        $data->setAxisName(0, "X(m)");
        $data->addPoints($timeseries->datasets[0]->data, "X");
        $data->setPalette("X",array("R"=>0,"G"=>0,"B"=>0,"Alpha"=>100));
        $X1 = 60;
        $X2 = 780;
        $Y1 = 25;
        $Y2 = 175;
        $image->setGraphArea($X1, $Y1, $X2, $Y2);
        $image->drawFilledRectangle($X1, $Y1, $X2, $Y2, [
            "R" => 255,
            "G" => 255,
            "B" => 255,
            "Alpha" => 0
        ]);
        $image->drawScale(["DrawSubTicks" => false, "LabelSkip" => $skipLabel]);
        $image->setShadow(true, ["X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10]);
        $image->drawLineChart(["DisplayValues" => false, "DisplayColor" => DISPLAY_MANUAL]);
        $image->setShadow(false);`

I hope this isn't just an issue with my configuration :)

PS - I've just checked my commit and I've noticed that I've changed the default font face. My mistake, please leave the default one if you find it more suitable.

**Comment by szymach** [comment]
Hey,
Sorry for the delay, I really had to take a break from programming. As to your issue, so I ran this code ( a bit modified version of what you have posted):

```php
$data = new Data();
$data->setAxisName(0, "X");
$data->setAxisDisplay(0, AXIS_FORMAT_METRIC);
$data->addPoints([-4, VOID, VOID, 12, 8, 3], "Date");
$data->setSerieDescription("Date", "Date");
$data->setAbscissa("Date");
$data->setXAxisDisplay(AXIS_FORMAT_DATE, "Y/m/d");

$image = new Image(800, 680, $data);
$image->setFontProperties(["FontName" => "calibri.ttf", "FontSize" => 10]);

$data->setAxisName(0, "X(m)");
$data->addPoints([3, 12, 15, 8, 5, -5], "X");
$data->setPalette("X", ["R" => 0, "G" => 0, "B" => 0, "Alpha" => 100]);
$X1 = 60;
$X2 = 780;
$Y1 = 25;
$Y2 = 175;
$image->setGraphArea($X1, $Y1, $X2, $Y2);
$image->drawFilledRectangle($X1, $Y1, $X2, $Y2, [
    "R" => 255,
    "G" => 255,
    "B" => 255,
    "Alpha" => 0
]);
$image->drawScale(["DrawSubTicks" => false, "LabelSkip" => 'skip']);
$image->setShadow(true, ["X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10]);
$image->drawLineChart(["DisplayValues" => false, "DisplayColor" => DISPLAY_MANUAL]);
$image->setShadow(false);
var_dump($image->FontName);
```

and it this was the result: `"/home/chuck/Projekty/c-pchart/src/../resources/fonts/calibri.ttf"`. How did you verify the font change? Am I doing something differently than you? Lastly, which version of the library are you using? Thanks.

**Comment by szymach** [comment]
Hey, since I cannot confirm this problem, I am closing the PR. Feel free to post again if you can provide a confirmable test case.

**Pull request closed without merging**
